// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_NORMALBTN_H
#define _UI_COMP_NORMALBTN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT normalBtn
#define UI_COMP_NORMALBTN_NORMALBTN 0
#define UI_COMP_NORMALBTN_BTNLABEL 1
#define _UI_COMP_NORMALBTN_NUM 2
lv_obj_t * ui_normalBtn_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
