// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT normalBtn

lv_obj_t * ui_normalBtn_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_normalBtn;
    cui_normalBtn = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_normalBtn, lv_pct(22));
    lv_obj_set_height(cui_normalBtn, lv_pct(13));
    lv_obj_set_x(cui_normalBtn, lv_pct(35));
    lv_obj_set_y(cui_normalBtn, lv_pct(37));
    lv_obj_set_align(cui_normalBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_normalBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_normalBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_normalBtn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_normalBtn, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_normalBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_normalBtn, lv_color_hex(0xDB661F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_normalBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_normalBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_normalBtn, lv_color_hex(0x7C3E18), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_normalBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_btnLabel;
    cui_btnLabel = lv_label_create(cui_normalBtn);
    lv_obj_set_width(cui_btnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_btnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_btnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_btnLabel, "Button");
    lv_obj_set_style_text_font(cui_btnLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NORMALBTN_NUM);
    children[UI_COMP_NORMALBTN_NORMALBTN] = cui_normalBtn;
    children[UI_COMP_NORMALBTN_BTNLABEL] = cui_btnLabel;
    lv_obj_add_event_cb(cui_normalBtn, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_normalBtn, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_normalBtn_create_hook(cui_normalBtn);
    return cui_normalBtn;
}

