// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_normalBtn = ui_normalBtn_create(ui_mainScreen);
    lv_obj_set_x(ui_normalBtn, lv_pct(35));
    lv_obj_set_y(ui_normalBtn, lv_pct(37));

    lv_label_set_text(ui_comp_get_child(ui_normalBtn, UI_COMP_NORMALBTN_BTNLABEL), "Hi");

    ui_scanBtn = ui_normalBtn_create(ui_mainScreen);
    lv_obj_set_x(ui_scanBtn, lv_pct(11));
    lv_obj_set_y(ui_scanBtn, lv_pct(37));


}
